### ISSUE TITLE
Error in Laravel

### ISSUE THREAD

**Issue by Retropartidas** [HuasoFoundries/jpgraph#126]
Hi friends. The first of all is to thank you for the work you are doing. A good graphics generation library for PHP was needed.

I have little knowledge of PHP and English is not my language but if I can help with something, I am delighted.

I have been using the previous version (4.0.3?) In Laravel 8 with PHP 8 for several months and I have had no problems creating bar and grid 

I just updated to this latest version and I have come across this general error that always happens to me.

```
PHP Fatal error:  Cannot redeclare ddd() (previously declared in C:\xampp\htdocs\laravel\vendor\facade\ignition\src\helpers.php:8) in C:\xampp\htdocs\laravel\vendor\amenadiel\jpgraph\src\includes\polyfills.php on line 53
```

I thank you again. I want you to know that there are many of us who use this library and we are very happy to know that it will continue to be updated. Thanks!

**Comment by ffflabs** [comment]
Sorry about that. I've released a hotfix (4.1.1) removing said function. It might take a few minutes to propagate to packagist...
