### ISSUE TITLE
Failed opening required 'jpgraph_imgtrans.php'

### ISSUE THREAD

**Issue by el-timm** [HuasoFoundries/jpgraph#13]
When trying to use the following line:
`$graph->Set3DPerspective(SKEW3D_UP,100,120,true);`

this error is thrown:
`PHP Warning:  require_once(jpgraph_imgtrans.php): failed to open stream: No such file or directory in /.../vendor/amenadiel/jpgraph/src/graph/Graph.php on line 1790`

That file has been renamed to images/ImgTrans.php in the src directory.

**Comment by el-timm** [comment]
Looks like the file is to change line 1790 from:
`require_once 'ImgTrans.php';`

to:
`dirname(__FILE__) . "/../image/ImgTrans.php";`

**Comment by amenadiel** [comment]
Let me see if we can deal with it using psr4 autoloader. I hate to use manual includes

**Comment by amenadiel** [comment]
@el-timm I believe I fixed it with https://github.com/HuasoFoundries/jpgraph/commit/a2561fbcf119bef17abbfcd55a689bb27ea8db28

please update to v3.6.8
