### ISSUE TITLE
Missing Class Rectangle error

### ISSUE THREAD

**Issue by mila76** [HuasoFoundries/jpgraph#15]
In varius file (plotband for example) you use "new Rectangle" instead of "new Util\Rectangle"

**Comment by amenadiel** [comment]
Are you interested in fixing this issue? As of now, I can't mantain this repo.

**Comment by amenadiel** [comment]
Solved in tag v3.6.10

**Comment by mila76** [comment]
Thanks man... sorry can do more... but i'm not so familiar with git and github....
