### ISSUE TITLE
Dashed Line

### ISSUE THREAD

**Issue by mila76** [HuasoFoundries/jpgraph#60]
From php7 i cant trace any dotted/dashed line
On linux work, on 5.x work

If i do the same raw GD (i dont have a debugger so something can miss) i can create dashed line

Probably is not related to Jpgraph himself but is someone can help on this....
Here the raw GD i can extrapolate

<?php
header("Content-type: image/png");

$im  = imagecreatetruecolor(800, 440);
imagealphablending($im, true);

$pts = [0, 0, 799, 0, 799, 439, 0, 439];
imagesetthickness($im, 1);
imagefilledpolygon($im, $pts, 4, 16777215);

$style = array(
    0 => 16711680,
    1 => 16711680,
    2 => 16711680,
    3 => 16711680,
    4 => 16711680,
    5 => 16711680,
    6 => 16711680,
    7 => 16711680,
    8 => 16711680,
    9 => -6,
    10 => -6,
    11 => -6,
    12 => -6,
);

imagesetthickness($im, 1);
imagesetstyle($im, $style);
imageline($im, 40, 265, 780, 265, IMG_COLOR_STYLED);

imagepng($im, null);
imagedestroy($im);

?>

**Comment by amenadiel** [comment]
Take a look at the examples such as [examples_background/background_type_ex0.php](https://github.com/HuasoFoundries/jpgraph/blob/master/Examples/examples_background/background_type_ex0.php)

I have no problem visualizing dashed grid lines:

```
$graph->SetAxisStyle(AXSTYLE_BOXOUT);

$graph->xgrid->SetLineStyle('dashed');
$graph->xgrid->Show(true);
$graph->ygrid->SetLineStyle('dashed');
$graph->ygrid->Show(true);
```

**Comment by mila76** [comment]
On windows i dont have that but this
![background_type_ex0 php](https://user-images.githubusercontent.com/378500/40322185-dca2033c-5d31-11e8-9318-812d8722f05e.png)

**Comment by amenadiel** [comment]
Uh, no clue. Perhaps the GD compilation on Windows isn't really platform agnostic, or there might be an intermediate issue if there's any hardware antialiasing involved.
