### ISSUE TITLE
kint-php/kint dependency

### ISSUE THREAD

**Issue by finnan444** [HuasoFoundries/jpgraph#63]
Despite the fact you mentioned kint-php/kint: ^2.2 as "requires (dev)" dependency it causes fatal error, if kint-php/kint: version 1.1 or lower installed. The problem is in
vendor/amenadiel/jpgraph/src/config.inc.php:758
```PHP
\Kint::$enabled_mode = DEBUGMODE;
```
This static property is undeclared in older versions of kint.

Plus,  i think it is a bad practice to declare a Class that mocks Kint inside config.inc.php.
What is the pupose, all the code with kint is commented like:
```PHP
//\Kint::dump($files[$i]);
```

**Comment by amenadiel** [comment]
I see your point. Since it's a dev dependency Kint wouldn't be installed when you require jpgraph, but if your project already has kint it will try to use the static property and things will blow up. 

I'm releasing a new version to address this problem

**Comment by amenadiel** [comment]
@finnan444 I agree it's kind of an antipattern to mock the class, but when I get some spare time I try to repair broken components of this library, for which I use quite a few debug and dump statements. I wouldn't like to release a version which breaks because I forgot to comment out those statements.

**Comment by amenadiel** [comment]
@finnan444 ouch, I just noticed I had this package under an old url in packagist.That's why it wasn't updating properly.

**Comment by finnan444** [comment]
@amenadiel I've just installed 3.6.21 and it works fine. But while testing your class disabled Kint globally, so i have to manually enable it during debugging =)
```PHP
\Kint::enabled(true);
ddd('Here');
```
Hope you fix all the bugs and remove the mockup class
