### ISSUE TITLE
Create tag v 4.0.0 pins to a upper version of symfony dotenv to run in PHP 7.2

### ISSUE THREAD

**Issue by koutja** [HuasoFoundries/jpgraph#68]
Please, pins to a upper version of symfony dotenv to run in PHP >= 7

**Comment by amenadiel** [comment]
I guess that's the way to go, since PHP 5.6 has reached EOF.

**Comment by amenadiel** [comment]
Done! https://github.com/HuasoFoundries/jpgraph/releases/tag/v4.0.0
