### ISSUE TITLE
about FF_USERFONT

### ISSUE THREAD

**Issue by cdmalcl** [HuasoFoundries/jpgraph#69]
class TTF 
function File
Can absolute paths be supported?

**Comment by ffflabs** [comment]
@cdmalcl  sorry it took me so long. I started refactoring and now I don't know how to merge god damned develop.

Having said that: The logic looks for the fontfiles on JPGraph's project root > src > fonts. If the requested font isn't found, it would search either in the path defined in the constant  `TTF_DIR` (or  `MBTTF_DIR` in a very specific case).

As of [**version 4.0.1**](https://github.com/HuasoFoundries/jpgraph/releases/tag/v4.0.1
), I'm uploading a hotfix to enable this feature. :+1: 


![image](https://user-images.githubusercontent.com/238439/71528821-8cd7b480-28c0-11ea-815f-9b2bba423afa.png)

The code for the graph above is at

https://github.com/HuasoFoundries/jpgraph/blob/86d9bd38a677d3fd894b6133f55166e68e71aafd/Examples/examples_multigraph/example_two_piecharts.php#L1-L97
