### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by yimengyisheng** [HuasoFoundries/jpgraph#71]
jpgraph_gb2312.php          This file does not exist

**Comment by ffflabs** [comment]
You're right, it was renamed and I missed a manual inclusion

https://github.com/HuasoFoundries/jpgraph/blob/86d9bd38a677d3fd894b6133f55166e68e71aafd/src/text/LanguageConv.php#L49-L50

I'm uploading a hotfix. However, it would be enough to comment said inclusion:

    // include_once 'jpgraph_gb2312.php'; 

And let composer do its magic.

**Comment by ffflabs** [comment]
@yimengyisheng Done. It's tag [**4.0.2**](https://github.com/HuasoFoundries/jpgraph/releases/tag/v4.0.2)
