### ISSUE TITLE
DotEnv should be optional

### ISSUE THREAD

**Issue by garak** [HuasoFoundries/jpgraph#82]
This library is requiring `symfony/dotenv`, but then it's working without it too.
So, such dependency should be moved from `require` to `require-dev` (and/or to `suggest`)

**Comment by ffflabs** [comment]
You're right. I made said change last night on release 4.0.3

https://github.com/HuasoFoundries/jpgraph/blob/1328d5a2cf0f1ce8f83b79f17d339b34241ace74/composer.json#L18-L30

Looking at the inclusion of DotEnv, I guess I envisioned changing (sooner or later) some of the 200+ constants of this library to environment variables, but I'm convinced anymore. 

After all, if someone wants to override one of jpgraph's constants, he just needs to define it before instancing the graph.
