### ISSUE TITLE
Display chart at a specific location on the page

### ISSUE THREAD

**Issue by thiMoreira** [HuasoFoundries/jpgraph#89]
I want to generate the graphic in a specific place on the page, but it always opens as if it were a modal, with a black background and showing only the graphic, covering the rest of the page. I looked for something in the documentation but I couldn't find it, could you help me? Thanks

**Comment by ffflabs** [comment]
The graph is generated as an image, you should be able to use it as an img tag in your html. I believe the csim examples use it that way (I'm barely getting to code some tests, remember this is a revival of an abandoned project)

**Comment by thiMoreira** [comment]
> The graph is generated as an image, you should be able to use it as an img tag in your html. I believe the csim examples use it that way (I'm barely getting to code some tests, remember this is a revival of an abandoned project)


thanks for being willing to help, researching more I found this way to generate the image in a specific directory and then call it in html, it worked, thanks!

Solution:
$graph-> Stroke ('./ assets / charts / chart_bar.png');
<img src='./ assets / charts / chart_bar.png'>
