### ISSUE TITLE
cannot find fonts

### ISSUE THREAD

**Issue by nicman23** [HuasoFoundries/jpgraph#92]
it throws this error

`JpGraph Error: 25092There is either a configuration problem with TrueType or a problem reading font file "/usr/share/fonts/TTF/DejaVuSans.ttf" Make sure file exists and is in a readable place for the HTTP process. (If 'basedir' restriction is enabled in PHP then the font file must be located in the document root.). It might also be a wrongly installed FreeType library. Try upgrading to at least FreeType 2.1.13 and recompile GD with the correct setup so it can find the new FT library.`

but phpinfo() shows it enabled and the file exists, with no basedir configuration (it is disabled on php.ini `open_basedir => no value => no value
`)

```
GD Support => enabled
GD headers Version => 2.3.0
GD library Version => 2.3.0
FreeType Support => enabled
FreeType Linkage => with freetype
```

i recompiled php, resulting in the same issue. also this is from php cli not apache etc.

**Comment by murrant** [comment]
I noticed I get this error when JpGraph tries to render an empty string...

**Comment by richardZhengGR** [comment]
the same error. @nicman23

**Comment by richardZhengGR** [comment]
yes, thank u. But i had no idea how to fix it few days ago. 
And finally I found out the problem is the GD library. and I did so.
In the path : **amenadiel\jpgraph\src\image\Image.php** 
function:
> _StrokeTTF()
$txt
> imagettfbbox_fixed()
 $text

 filter parameters $txt &  $text in the function like this:
```
        if($text == ''){
            $text = '  ';
        }
```

**Comment by richardZhengGR** [comment]
> I noticed I get this error when JpGraph tries to render an empty string...

yes, thank u murrant. But i had no idea how to fix it few days ago. 
And finally I found out the problem is the GD library. and I did so.
In the path : **amenadiel\jpgraph\src\image\Image.php** 
function:
> _StrokeTTF()
$txt
> imagettfbbox_fixed()
 $text

 filter parameters $txt &  $text in the function like this:
```
        if($text == ''){
            $text = '  ';
        }
```

**Comment by octoquad** [comment]
@murrant @richardZhengGR, thanks for providing workarounds. Both work, even with JPGraph 3.0.7!

@murrant your fix will still emit a PHP warning:  `PHP Warning:  imagettftext(): Problem doing text layout in ...` but still renders the graph correctly.

**Comment by ffflabs** [comment]
I'd still like to know how to reproduce this issue. I tried manually setting wrong titles and legends to no avail. 

Is this one of those bugs that won't manifest themselves in testing or mocking environments?
