### ISSUE TITLE
PHP 7.4 not supported

### ISSUE THREAD

**Issue by s-dera** [HuasoFoundries/jpgraph#94]
Can You Please Update it to last version of JpGraph to JpGraph-4.3.0-pro (4.3.0-pro) because its supporting PHP 7.4.
Thanks,

**Comment by nicgordon** [comment]
This would be great. I'd love to install JPGraph via composer if possible.

**Comment by MisterDuval** [comment]
use https://packagist.org/packages/amenadiel/jpgraph

**Comment by formikaio** [comment]
> use https://packagist.org/packages/amenadiel/jpgraph

this addresses the request of "install JPGraph via composer" but doesn't address the topic issue "PHP 7.4 not supported"

**Comment by formikaio** [comment]
#106
