### ISSUE TITLE
imagecolorresolvealpha() expects parameter 2 to be int, string given 

### ISSUE THREAD

**Issue by ettr** [HuasoFoundries/jpgraph#95]
Passing multiple colors to a Radar graph's titles results in an imagecolorresolvealpha error. (vendor/amenadiel/jpgraph/src/image/RGB.php:586)

my Code:
$titles is an array of 11 string values
$colors is an array of 11 string values (e.g. 'black','blue','green',...)
$data is an array of 11 ints between 0 and 3

`
$graph = new Graph\RadarGraph(1140, 850);
$graph->SetCenter(0.52, 0.5);
$graph->SetScale('lin', 0, 3);
$graph->SetFrame(false);
$graph->legend->SetPos(0.77,0.02,'left','top');
$graph->legend->SetFont(FF_ARIAL,FS_NORMAL,16);
$graph->SetTitles($titles);
$graph->axis->SetFont(FF_ARIAL,FS_BOLD,12);
$graph->axis->SetWeight(2);
$graph->axis->title->SetFont(FF_ARIAL,FS_BOLD,12);
$graph->axis->SetColor('black', $colors);
$graph->axis->scale->ticks->Set(1,2,3);
$graph->grid->Show ();
$teamPlot = new Plot\RadarPlot($data);
$teamPlot ->SetColor('blue','lightblue');
$teamPlot ->SetLegend('Initial Assessment');
$graph->Add($teamPlot);
$img = $graph->Stroke(_IMG_HANDLER);
ob_start();
imagepng($img);
$img_data = ob_get_contents();
ob_end_clean();
$img_data = base64_encode($img_data);
return($img_data);
`

**Comment by ffflabs** [comment]
@ettr I know it took me a lot to answer, but here it goes.

`RadarAxis::SetColor` expects a color as the second parameter, which can be passed as a string or as a numeric array representing [$r, $g, $b, $alpha]

when you passed an array of strings it crashed when it tried to apply a non numeric alpha transparency (your fourth color)

I'm not sure there's a way, currently, to colorize each radar axis with its own color, nor each one with a gradient and most probably, neither the grids. What you might be able to do, on the other side, is colorize the ticks, which could at least provide a decent visual cue.
