### ISSUE TITLE
composer autoload deprecation warnings

### ISSUE THREAD

**Issue by formikaio** [HuasoFoundries/jpgraph#97]
`composer install` complains about non-compliant classes:
- Amenadiel\JpGraph\UnitTest\UnitTester located in tests/_support/UnitTester.php
- Amenadiel\JpGraph\UnitTest\Helper\Unit located in tests/_support/Helper/Unit.php
- Amenadiel\JpGraph\UnitTest\_generated\UnitTesterActions located in tests/_support/_generated/UnitTesterActions.php 

For each class `composer` shows this Deprecation notice: `Class does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.`

Composer version: 1.10.13

The only classes affected are in the UnitTest namespace, so this probably won't affect actually running jpgraph in production.

**Comment by ffflabs** [comment]
yeah, that namespace is for tests only and should be now excluded from the composer's tarball package that ultimately gets to your repo now

**Comment by ffflabs** [comment]
@all-contributors please add @formikaio for bugs

**Comment by ffflabs** [comment]
closed by #101
